[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

###################################
######### Project Setting #########
###################################
[project]
name = "lakehouse_demo_project"
version = "0.1.0"
description = "A Databricks Asset Bundle using Hatch"
authors = [{ name = "Rasmus Holm Laursen", email = "rasmus.h.laursen@twoday.com" }]
dependencies = [
    "databricks-sdk",
    "setuptools",
    "faker == 37.6.0",
    "databricks.labs.dqx == 0.11.1",
    "pydantic",
    "pyyaml",
    "datacontract-cli",
    "python-dotenv"
]

[project.scripts]
source = "src.main:main"
synthetic_data_contracts = "src.synthetic_data_contracts:main"
metric_view = "src.curated.metrics.lakehouse_metric:create_lakehouse_metric_view"

[tool.hatch.build.targets.wheel]
packages = ["src/"]

[tool.converge.paths]
source = ["src/"]

[tool.pylance]
reportCallIssue = "none"

######################################
######### Hatch Environments #########
######################################

## LINTING ##
[tool.hatch.envs.lint]
dependencies = ["black"]

[tool.hatch.envs.lint.scripts]
run = "black . --check"
fix = "black ."

## TYPE CHECKING ##
[tool.hatch.envs.typecheck]
dependencies = ["mypy"]

[tool.hatch.envs.typecheck.scripts]
run = "mypy ."

## UNIT TESTS#
[tool.hatch.envs.unit_tests]
dependencies = [
    "pytest",
    "pyspark",
    "databricks-connect",
    "faker == 37.6.0",
    "databricks-sdk",
    "pydantic",
    "pyyaml"
]

[tool.hatch.envs.unit_tests.scripts]
run = "pytest tests/unit/helper_test/config_test.py"

## ACCEPTANCE TESTS##
[tool.hatch.envs.acceptance_tests]
dependencies = [
    "behave",
    "databricks-sdk"
]

[tool.hatch.envs.acceptance_tests.scripts]
run = "behave documentation/features"

## DEVELOPMENT ENVIRONMENTS ##
[tool.hatch.envs.development_local]
dependencies = ["databricks_connect"]

[tool.hatch.envs.development_local.scripts]

validate_pipeline = "databricks bundle run lakehouse_demo_project_pipeline --validate-only -t developer"
deploy = "databricks bundle deploy -t developer"
refresh_all_pipeline = "databricks bundle run lakehouse_demo_project_pipeline --refresh-all -t developer"
full_refresh_all_pipeline = "databricks bundle run lakehouse_demo_project_pipeline --full-refresh-all -t developer"
run = "databricks bundle run -t developer"

## DATABRICKS ENVIRONMENTS ##
[tool.hatch.envs.databricks.scripts]
validate = "databricks bundle validate"
deploy = "databricks bundle deploy --auto-approve"
run = "databricks bundle run"

## APP STREAMLIT ENVIRONMENTS ##
[tool.hatch.envs.app_development]
dependencies = [
    "streamlit",
    "pandas",
    "faker == 37.6.0",
    "databricks-sql-connector"
]

[tool.hatch.envs.app_development.scripts]
run = "cd src/app_streamlit && streamlit run app.py"


##############################
######### Deploy app #########

## DATABRICKS ENVIRONMENTS ##
[tool.hatch.envs.databricks-app.scripts]
validate = "databricks bundle validate"
deploy = "databricks bundle deploy --auto-approve"
run = "databricks bundle run"
