customer:
  keys:
    - customer_id
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2
lakehouse:
  keys:
    - lakehouse_id
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2
lakehouse_rentals:
  keys:
    - rental_id
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2
seller:
  keys:
    - seller_id
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2
loyalty_tier:
  keys:
    - loyalty_tier_id
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2
payment_method:
  keys:
    - payment_method_id  
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2
meta_region:
  keys:
    - region_name_id
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2
meta_lakehouses:
  keys:
    - lakehouse_name_id
  sequence_column: _metadata["ingest_timestamp"]
  stored_as_scd_type: 2  