<table_name>: # name of the table to be ingested
  keys: # what keys uniquely identify a record
    - <primary_key_column> # primary key column name
  sequence_column: <time> # what column indicates the latest version of a record
  stored_as_scd_type: 1 # what type of slowly changing dimension to use (1 or 2)