command: ["streamlit", "run", "app.py"]

env:
  - name: ENVIRONMENT
    valueFrom: ${var.environment}
  - name: LANDING_CATALOG
    value: ${var.landing_catalog}
  - name: BASE_CATALOG
    value: ${var.base_catalog}
  - name: RAW_CATALOG
    value: ${var.raw_catalog}
  - name: ENRICHED_CATALOG
    value: ${var.enriched_catalog}
  - name: CURATED_CATALOG
    value: ${var.curated_catalog}
  - name: WAREHOUSE_ID
    value: ${var.warehouse_id}
  - name: BOOKINGS_LANDING_SCHEMA
    value: bookings_landing_${var.environment}
  - name: BOOKINGS_RAW_SCHEMA
    value: bookings_raw_${var.environment}
  - name: BOOKINGS_BASE_SCHEMA
    value: bookings_base_${var.environment}