name: Deploy Lakehouse_Demo_Project

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to (e.g., dev, prod)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Deploying to ${{ inputs.enviroment }} environment"
      #   enviroment: ${{ inputs.enviroment }}
      #   command: databricks:deploy
      # secrets: inherit