name: Deploy Lakehouse_Demo_Project

on:
  workflow_call:
    inputs:
      enviroment:
        description: 'The environment to deploy to (e.g., dev, prod)'
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Deploying to "
      #   enviroment: ${{ inputs.enviroment }}
      #   command: databricks:deploy
      # secrets: inherit