name: Deploy Lakehouse_Demo_Project

on:
  workflow_call:
    inputs:
      enviroment:
        description: 'The environment to deploy to (e.g., dev, prod)'
        required: false
        type: string
jobs:
  dev:
    uses: ./.github/workflows/deploy_databricks.yml
    with:
      enviroment: 'dev'
    secrets: inherit
  tst:
    needs: dev
    uses: ./.github/workflows/deploy_databricks.yml
    with:
      enviroment: 'tst'
    secrets: inherit