name: Deploy Lakehouse_Demo_Project

on:
  workflow_call:
    inputs:
      enviroment:
        description: 'The environment to deploy to (e.g., dev, prod)'
        required: true
        type: string

jobs:
  hatch:
    name: Run hatch command
    runs-on: ubuntu-latest
    # enviroment: ${{ inputs.enviroment }}

  deploy:
    name: Deploy to ${{ inputs.enviroment }} environment
    uses: ./.github/workflows/hatch.yml
    with:
      enviroment: ${{ inputs.enviroment }}
      command: databricks:deploy
    secrets: inherit