name: Deploy Databrikcs solution
on: 
  push:
    branches:
      - feature/**
      - main
  
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

jobs: 
  dev:
    uses: ./.github/workflows/deploy.yml
    with:
      enviroment: 'dev'
    secrets: inherit

  tst:
    uses: ./.github/workflows/deploy.yml
    with:
      enviroment: 'tst'
    secrets: inherit