name: Deploy Databrikcs solution
on: 
  push:
    branches:
      - feature/**
      - main
  
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Deploy to dev 
      #   uses: ./.github/workflows/deploy.yml
      #   with:
      #     enviroment: dev
      - name: Print environment
        run: echo "Deploying to ${{ inputs.enviroment }} environment"      