name: Deploy Databrikcs solution
# on: 
#   push:
#     branches:
#       - feature/**
#       - main
  
#   pull_request:
#     branches:
#       - '**'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Deploying to ${{ inputs.environment }} environment"          
      - name: Deploy to dev 
        uses: ./.github/workflows/deploy.yml
        with:
          environment: dev
