name: Deploy Databrikcs solution
on: 
  push:
    branches:
      - feature/**
      - main
  
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Deploying to "
  hatch:
    uses: ./.github/workflows/hatch.yml
    with:
      enviroment: 'tst'
      command: 'deploy'
    secrets: inherit